project-robius/robrix

src/home/rooms_list.rs
src/sliding_sync.rs

Downloading the avatar image from the server works, but they are not displayed correctly for each room preview.

Download and display room avatars in list of all room previews

---

Cargo.lock
Cargo.toml
src/home/room_screen.rs
src/home/rooms_list.rs
src/shared/avatar.rs
src/sliding_sync.rs
src/utils.rs

* Send status updates and connection errors to be displayed by the RoomsList.
* temp: add DEBUG messages everywhere to help debug issues with makepad font rendering.

Display proper avatars and usernames for all event types, when available

---

src/home/room_screen.rs

This avoids locks and unnecessary wrappers around the timeline state. The `TimelineUiState` is retrieved and stored into the `Timeline` when the room is showed, and then removed from the `Timeline` and restored back to the global `TIMELINE_STATES` map when the room is hidden.

Store an owned `TimelineUiState` directly in the `Timeline` widget.

---

Cargo.lock
Cargo.toml
src/home/room_screen.rs
src/shared/html_or_plaintext.rs
src/shared/styles.rs

Remove old message menu of likes/reply button, which aren't used.

Show reactions (annotations) as plaintext beneath each message.

---

Cargo.lock
src/app.rs
src/contacts/add_contact_screen.rs
src/home/rooms_list.rs
src/profile/my_profile_screen.rs
src/profile/profile_screen.rs
src/shared/avatar.rs
src/shared/html_or_plaintext.rs
src/shared/styles.rs

Still need to fix the TextInput shading/coloring in the message input box and in the search box up top.

Update to latest makepad and fix DSL formatting that is now required

---

Cargo.lock
Cargo.toml

The HtmlLink now emits an action that includes the URL of the link that was clicked.

Use our new design for Makepad HtmlLink handling

---

rust-toolchain.toml
src/profile/user_profile.rs

Fix outdated rust-toolchain file. Misc cleanup

---

Cargo.lock
Cargo.toml
src/home/room_screen.rs
src/home/rooms_list.rs
src/profile/user_profile.rs
src/sliding_sync.rs
src/utils.rs

This is required before we can attempt to solve the issue of timelines being cleared after an ignore/unignore user action completes, and we need to re-paginate the timelines.
We also need the newer SDK functions to implement jumping to a specific event in a specific room, such that we can implement a "focused" mode in which the Timeline is focused on displaying a specific event. When doing so, we need the new paginate forwards/backwards functions to fill in the missing context from that point.
Currently this builds, and all structural changes have been made for SDK update, but nothing has been tested yet.

Update Matrix SDK to latest version

---

Cargo.lock
src/home/room_screen.rs
src/sliding_sync.rs

We recently added a few new methods:
* `PortalList::next_visible_item_with_scroll()`
* `PortalList::is_at_end()`

Update to include some new PortalList changes

---

src/home/room_screen.rs

This was accidentally deleted during a recent merge.

Restore accidentally-removed jump to bottom button action

---

Cargo.lock
Cargo.toml
src/app.rs
src/home/room_screen.rs
src/shared/adaptive_layout_view.rs
src/shared/html_or_plaintext.rs
src/shared/mod.rs
src/shared/search_bar.rs

Remove unused modules: popup, modal, dropdown_menu, portal

Upgrade Makepad to latest `rik` branch

---

src/home/room_screen.rs

~~WIP, untested.~~ tested and working now
Addresses #132

Combine Timeline into RoomScreen and remove `Timeline` struct

---

Cargo.lock
Cargo.toml
src/home/main_content.rs
src/home/room_screen.rs
src/shared/adaptive_layout_view.rs

Note: we still need to re-draw the replying_to preview upon restore.

Simplify showing/hiding rooms. Save full state of text input and reply preview

---

Cargo.lock
src/home/room_screen.rs
src/home/rooms_list.rs
src/home/welcome_screen.rs
src/shared/adaptive_layout_view.rs
src/shared/html_or_plaintext.rs

It doesn't yet support colorizing the text, so we comment out those parts, for now.

Use new `HtmlLink` widget which preserves TextFlow formatting

---

Cargo.lock
Cargo.toml
src/home/room_preview.rs
src/home/room_screen.rs
src/home/rooms_list.rs
src/persistent_state.rs
src/shared/html_or_plaintext.rs
src/sliding_sync.rs
src/utils.rs

Closes #18 
among many other improvements, remove the optionality of room ID within `RoomPreviewEntry`, as that field is always required.

Switch to simplified sync service

---

src/home/room_screen.rs
src/shared/mod.rs
src/shared/styles.rs
src/shared/type_loading.rs
src/shared/typing_animation.rs

Animation effects have been added, but they still need to be beautified.

Add an animated ellipsis for Users are typing

---

src/login/login_screen.rs
src/persistent_state.rs
src/shared/avatar.rs
src/sliding_sync.rs

Ensure that avatar images are stretched to fill a perfect circle.

Add more details to status messages shown on the login screen.

---

src/home/room_screen.rs

Make the calculation of typing messages more efficient, especially when processing many typing notice updates.

Cleanup handling of typing notice view animation

---

Cargo.lock
src/login/login_screen.rs

Now used for the login password field.

Update makepad to support secret TextInput fields

---

Cargo.lock
Cargo.toml
src/home/room_screen.rs
src/home/rooms_list.rs
src/home/welcome_screen.rs
src/login/login_screen.rs
src/sliding_sync.rs
src/verification.rs

Suppors the new `RoomList::dynamic_entries_with_adapters()` which is _far_ more complex than `entries()`.

Upgrade to newer SDK version that has removed `RoomList::entries()`

---

Cargo.lock
Cargo.toml
src/home/room_screen.rs
src/shared/icon_button.rs
src/shared/jump_to_bottom_button.rs
src/shared/mod.rs
src/shared/styles.rs

Add new design that exposes a simpler API, which prevents errors like forgetting to update the visibility state of both the jump to bottom parent view *and* the unread message badge view.

Refactor jump to bottom button into its own file

---

src/home/room_screen.rs

We don't yet support actual playback of audio and video, but it's better to show something rather than an empty space.

Display basic info for Audio and Video messages

---

src/home/room_screen.rs
src/home/spaces_dock.rs
src/shared/adaptive_view.rs
src/shared/jump_to_bottom_button.rs
src/sliding_sync.rs
src/verification.rs

Make sure we pass the typo check and wait to add to the CI base configuration.

Modify document typos

---

src/home/rooms_list.rs

RoomsList: ensure the count of loaded rooms is always correct

---

src/home/loading_modal.rs
src/home/room_screen.rs
src/sliding_sync.rs

Fixes #279 
* Add function to easily get the currently-logged in user.
* Specify cursors for views used in the RoomScreen, which forces Makepad to reset the hover-out cursor properly.

Highlight messages with `@room` mentions

---

src/login/login_screen.rs

Also, don't perform an early check for UserID validity, since we also want to allow the user to entire a partial UserID (with just the local part) that we can then auto-append the homeserver URL to in the backend before submitting the login request.

Improve login screen: allow scrolling, better layout

---

Cargo.lock
Cargo.toml
src/shared/html_or_plaintext.rs

Fixes #274 and addresses other parts of #63

Support drawing spoiler messages and background text colors

---

Cargo.lock
Cargo.toml

Patch `imbl` to fix their bug in `Focus::narrow()`

---

src/home/room_screen.rs

This pr fix thumbnails' displaying.
It's more blurry than lastest main.

Fix thumbnails' displaying

---

src/home/room_preview.rs
src/home/room_screen.rs
src/home/rooms_list.rs

Bottom-align buttons in message input bar

---

src/app.rs
src/login/login_screen.rs
src/login/login_status_modal.rs

Upon login, close the login_status_modal in all possible action handlers

---

src/home/room_preview.rs

Added wider badge for unread message count > 99 room preview

---

src/home/new_message_context_menu.rs
src/home/room_screen.rs
src/shared/styles.rs

No dedicated emoji picker yet, but you can send one via copy & paste

Allow sending custom text reactions (including emoji)

---

src/home/room_screen.rs

fix out of bound when sending read receipt

---

src/app.rs

change title into robrix

---

Cargo.lock
Cargo.toml
src/home/room_screen.rs

Fixes #388
https://github.com/user-attachments/assets/b05ac8f8-5b7d-471b-910d-68affbbc58bd

Draw the blurhash while waiting for an image to be fetched

---

README.md

reomve known issue title named makepad

---

src/home/editing_pane.rs
src/home/mod.rs
src/home/new_message_context_menu.rs
src/home/room_screen.rs
src/sliding_sync.rs

~~WIP. Untested.~~
Works for all basic event types. Will need more support in the future for editing poll answers, or non-text/emote Message types.
Closes #404.

Support editing messages

---

src/home/room_screen.rs
src/sliding_sync.rs

Fixes #315 
Added Task_handle's abort function to close the loop waiting for own read receipts changes.

Unsubscribe to own read receipt when closing the room

---

Cargo.lock
Cargo.toml
src/home/room_screen.rs
src/media_cache.rs
src/persistent_state.rs
src/sliding_sync.rs
src/utils.rs

Needed for various new features.

Upgrade to latest matrix-rust-sdk version

---

src/home/room_screen.rs
src/shared/typing_animation.rs

This removes unnecessary redraws of the parent view stack too.

Properly implement the TypingAnimation using shader timing

---

src/home/room_screen.rs
src/media_cache.rs
src/shared/text_or_image.rs
src/sliding_sync.rs

Fix issue405: [Refactor MediaCache](https://github.com/project-robius/robrix/issues/405)

Redesign MediaCache to support holding both thumbnails and full-size images for a given `MxcUri`.

---

Cargo.lock
src/app.rs
src/home/editing_pane.rs
src/home/event_reaction_list.rs
src/home/light_themed_dock.rs
src/home/loading_pane.rs
src/home/new_message_context_menu.rs
src/home/room_preview.rs
src/home/room_screen.rs
src/home/rooms_sidebar.rs
src/home/spaces_dock.rs
src/login/login_screen.rs
src/login/login_status_modal.rs
src/profile/user_profile.rs
src/shared/callout_tooltip.rs
src/shared/helpers.rs
src/shared/icon_button.rs
src/shared/jump_to_bottom_button.rs
src/shared/mentionable_text_input.rs
src/shared/popup_list.rs
src/shared/search_bar.rs
src/shared/styles.rs
src/verification_modal.rs

Accommodate new themes and DSL names, mostly in shaders.

Update Makepad again, fix more event handling

---

src/home/room_screen.rs
src/shared/mentionable_text_input.rs

`@room` mentions not yet supported.
Closes #449 
~~Todo: restore recent changes from `main`~~

Attach selected user ID mentions to messages

---

Cargo.lock
Cargo.toml
src/home/light_themed_dock.rs
src/shared/avatar.rs
src/shared/mentionable_text_input.rs

Update makepad to include our fixes to Android long-press

---

.github/workflows/main.yml
README.md

Add instructions for building on iOS simulator/device

---

src/home/loading_pane.rs
src/home/room_screen.rs
src/login/login_status_modal.rs
src/profile/user_profile.rs
src/room/room_input_bar.rs
src/shared/icon_button.rs
src/shared/mentionable_text_input.rs
src/shared/search_bar.rs
src/shared/styles.rs
src/shared/verification_badge.rs
src/verification_modal.rs

Adjust input bar spacing, margins, and layout.
Migrate all buttons/icons to RobrixIconButton

Adjust input bar layout, unify colors

---

src/home/location_preview.rs
src/home/mod.rs
src/home/room_screen.rs

Working towards simplifying the `RoomScreen` into a less-complex megalith.

Move `LocationPreview` into a separate module

---

.github/workflows/main.yml

Remove `check` job in Github Workflows

---

Cargo.lock
Cargo.toml
src/home/room_screen.rs

Fixes #487. 
In an empty message input box at the bottom of a RoomScreen, you can now press the Up arrow key to start editing the latest message that you sent.

Allow editing a recently-sent message by pressing the Up arrow

---

Cargo.lock
Cargo.toml
src/home/rooms_list.rs

Upgrade other deps to eliminate unnecessary duplicates in lockfile.

Upgrade makepad to fix ab_glyph_rasterizer bug

---

src/avatar_cache.rs
src/home/invite_screen.rs
src/home/room_screen.rs
src/home/spaces_dock.rs
src/lib.rs
src/profile/user_profile_cache.rs
src/shared/avatar.rs
src/shared/styles.rs
src/shared/verification_badge.rs

~~Not ready to merge; untested~~ works well
Clicking on it will (eventually) show a settings screen, but that is currently a WIP and doesn't exist yet.

Show actual user profile info in ProfileIcon in SpacesDock

---

src/app.rs
src/home/invite_screen.rs
src/home/main_desktop_ui.rs
src/home/room_screen.rs
src/persistent_state.rs
src/sliding_sync.rs

Fixes #554 
https://github.com/project-robius/robrix/pull/422

Change persistent state type from SavedDockState to AppState.

---

resources/icons/cloud_checkmark.svg
resources/icons/cloud_offline.svg
src/home/rooms_list_header.rs
src/settings/account_settings.rs
src/shared/styles.rs
src/sliding_sync.rs
src/tsp/tsp_settings_screen.rs

TSP: show default DID in the TspSettingsScreen.

Show sync status icons with offline error message

---

Cargo.lock
Cargo.toml
src/event_preview.rs
src/home/room_screen.rs
src/home/rooms_list_header.rs
src/profile/user_profile.rs
src/sliding_sync.rs
src/utils.rs

~~Temporarily disabled TSP stuff because it was causing version conflicts~~ working now with a new sqlx  patch that upgrades to libsqlite3-sys v0.35

Upgrade to latest matrix-sdk, matrix-sdk-ui, and ruma

---

src/home/room_screen.rs
src/sliding_sync.rs

Fix loading pane behavior, make timeline updates more efficient

---

Cargo.lock
src/home/room_screen.rs
src/room/mod.rs
src/room/typing_notice.rs
src/shared/bouncing_dots.rs
src/shared/mentionable_text_input.rs
src/shared/mod.rs

Rename TypingAnimation to "BouncingDots", as it is used elsewhere for non-typing-specific UI components.
Working towards #519

Refactor typing notice out of RoomScreen
