src/app.rs, src/home/mod.rs, src/home/room_screen.rs, src/home/rooms_list.rs, src/shared/stack_navigation.rs
Collapse `TopSpace` within the timeline view.
Properly rename `chat_screen` to `room_screen`
=> Improve rooms list to use actual server-side room names

Cargo.lock, Cargo.toml, src/app.rs, src/home/room_screen.rs, src/home/rooms_list.rs, src/shared/stack_navigation.rs, src/sliding_sync.rs
Currently we just use a basic UI signal for this, but we can definitely be smarter and more efficient about it in the future.
Upgraded to latest commit from the `rik` branch of makepad.
=> Auto-refresh rooms list view upon a background room update

src/home/rooms_list.rs, src/lib.rs, src/sliding_sync.rs
* The RoomsList widget now handles these updates:
* adding a new room
* updating the room's name
* updating the room's avatar
* any event occurring (which becomes the "latest" event)
* We now spawn a separate async task to fetch room avatar images, which speeds up handling large batches of updates in the main sync loop.
* The RoomsList now handles updates in the `handle_event()` callback
instead of in the draw function, which is better, faster, easier to understand,
and more similar to how timeline widgets handle their updates.
* Address all compiler warnings, just to assuage the worrisome :)
=> Fully update list of all rooms for any event that affects a room preview

src/home/room_screen.rs, src/sliding_sync.rs
Thus, there is no need to do a full room member fetch/sync upon viewing a room for the first time, which is good because that is *incredibly* slow for large rooms.
=> Enable lazy loading of user profiles for only the room members that have sent events

Cargo.lock, src/app.rs, src/home/room_screen.rs, src/lib.rs, src/shared/dropdown_menu.rs, src/shared/popup_menu.rs, src/sliding_sync.rs
* There's no need to have the Timeline UI widget do this as part of a UI action handler. Instead, we now apply the incoming timeline diffs to the timeline items list within a background async task, and then just send a reference to the update items list to the UI threads using the existing `TimelineUpdate` sender.
* Also, update to latest Makepad version.
=> Move timeline item management into a background async task

src/home/room_screen.rs, src/shared/avatar.rs
Currently works perfectly for text avatars and square image avatars, but rectangular images aren't quite masked properly, as their dimensions are based on the dimensions of the image, not the avatar view.
=> Mask all avatars with a circle

src/app.rs, src/home/room_screen.rs, src/home/rooms_list.rs, src/shared/avatar.rs
* Enable auto-tail to auto scroll to display new message if the timeline was already scrolled to the end of the list.
* Minor improvements to display of status messages, but the `apply_over()` function doesn't accept the `Fill`/`Fit` values for the `Size` enum that we actually need to use.
=> Clear message input box after sending message

.cargo/config.toml, .gitignore, Cargo.lock, Cargo.toml, README.md, login.toml, src/app.rs, src/home/room_screen.rs, src/home/rooms_list.rs, src/media_cache.rs, src/message_display.rs, src/sliding_sync.rs, src/utils.rs
Currently vendoring rusqlite and openssl-src so we can build them locally with the same NDK toolchain currently specified by `cargo-makepad`.
Error running 'robrix':
Activity class {dev.makepad.robrix/MakepadApp} does not exist
=> Support building and running on Android

Cargo.lock, src/app.rs
This is more appropriate than doing so when the App widget is created, as that can happen multiple times on Android, e.g., when switching apps.
=> Start background matrix sync tasks on the `Startup` event

Cargo.lock, Cargo.toml, README.md, src/home/room_screen.rs, src/sliding_sync.rs
Seems to be working well.
However, it could be more efficient by having the background timeline subscriber task include some information about where the changes were made, which would allow us to avoid searching the entire timeline list for the ID of the event that was previously shown at the top.
Also added some infra for avoiding redundant drawing work based on whether a timeline item has been changed in the background, but that is not yet being used.
=> Stable positioning of timeline items across background updates

src/app.rs, src/home/room_screen.rs, src/media_cache.rs, src/shared/avatar.rs, src/shared/mod.rs, src/shared/text_or_image.rs, src/sliding_sync.rs
* This allows us to use the same DSL widget view for image messages regardless of whether they can be successfully displayed or not. This simplifies caching of widgets both internal and external to a timeline's portallist, which will be implemented in an upcoming PR.
=> Add `TextOrImage` widget that can be used to display an image or text

src/home/room_screen.rs, src/home/rooms_list.rs
This is strictly better than showing/hiding a room upon the `set_displayed_room()`, which might be too early in the event flow.
There are still some minor issues with the StackNavigation widget not delivering all show/hide actions if you navigate *very quickly* back and forth between a stacknav view and the root_view, but that requires a separate fix.
=> Use stack navigation actions to show/hide a room timeline

src/home/room_screen.rs
Fixes #48.
This makes code simpler in the timeline drawing logic functions:
* `fn populate_redacted_message_view()`
* `fn populate_membership_change_view()`
* `fn populate_profile_change_view()`
* `fn populate_other_state_view()`
=> Deduplicate code across functions that populate small state event views

Cargo.toml, rust-toolchain.toml
Pin compiler version to avoid weird nightly discrepancies.
=> Make building on Windows x64 easier

Cargo.lock, Cargo.toml
This VASTLY simplifies building for Android and Windows targets.
=> Remove native dependencies in favor of rustls and sqlite-bundled

src/home/room_screen.rs
Mimetypes are not always correct. Since it's cheap to check the first few bytes of the image data array to determine the image file format, we just always do that up front, and ignore the mimetype entirely.
=> Don't rely on mimetypes to load image data

Cargo.lock, src/home/room_screen.rs, src/home/rooms_list.rs, src/shared/html_or_plaintext.rs, src/shared/styles.rs, src/utils.rs
Improve other message formatting, such as block quotes and code.
=> Use local timezone. Fix inline code formatting.

Cargo.lock, Cargo.toml, README.md, src/app.rs, src/home/room_screen.rs
* README: add Robrix chat room link and table of supported host+target pairs.
* Disable useless log messages, e.g., app lifecycle events.
* Make text input in a room timeline view much nicer visually with better colors and default formatting.
=> Support sending markdown messages, plus other misc improvements.

src/home/room_screen.rs, src/profile/user_profile.rs
Events that flow into the RoomScreen either get forwarded to the underlying timeline view or the user profile sliding pane. If the pane is currently shown, mouse/touch/tap events are forwarded to the pane *ONLY*, and not the underlying timeline. Other events (e.g., draw events) are always forwarded to the underlying timeline.
If the pane is not shown, events are also forwarded to the timeline view, as normal.
Solution suggested by @jmbejar.
=> Properly handle events when the user profile pane is shown

Cargo.lock, src/profile/user_profile.rs, src/sliding_sync.rs
Ignoring/unignoring a user does actually work, but the timelines are automatically cleared by the Matrix SDK, which Robrix currently doesn't handle very well.
Also, the newly re-fetched `RoomMember` object for the ignored user does NOT actually reflect that the user has been ignored, i.e., the `RoomMember::is_ignored()` function still returns the old state. Not sure how to fix that yet, but I am asking around.
=> Support some action buttons in the UserProfileSlidingPane.

Cargo.lock, src/profile/user_profile.rs, src/shared/modal.rs, src/shared/portal.rs, src/sliding_sync.rs
See this: <https://github.com/makepad/makepad/pull/497>
Also, clean up extraneous logging from prior PRs.
=> Use new Makepad version to reduce/remove clones and mutable pre-borrows

src/home/room_screen.rs, src/profile/user_profile.rs, src/sliding_sync.rs
Logic is incomplete for jumping to a different room because we need additional features from Makepad's StackNavigation widget in order to programmatically hide/show a different room.
=> Dedup/simplify logic for handling MatrixToUri and MatrixUri

src/media_cache.rs, src/profile/user_profile.rs
Previously only a different type of event (e.g., scroll, draw, etc) would result in an UI update for efficiency's sake, but that resulted in stale UI elements.
=> Update UI via a UI Signal upon background fetch of media or user profile

src/home/room_screen.rs, src/sliding_sync.rs
Handles UI-level actions emitted by the message input box widget, and submits an async request to send a "typing notice" to the current timeline's Room based on whether there is text present in the box.
=> Send a typing notice event when the user starts typing

src/home/room_screen.rs, src/profile/mod.rs, src/profile/user_profile.rs, src/profile/user_profile_cache.rs, src/shared/avatar.rs, src/sliding_sync.rs
Require functions that must run on the main UI thread to accept a reference to `Cx` as a guarantee that they are running on the main thread, as `&mut Cx` is only available on the main UI thread.
(untested)
=> Move user profile cache to its own module.

src/avatar_cache.rs, src/home/room_screen.rs, src/lib.rs, src/media_cache.rs, src/profile/user_profile.rs, src/profile/user_profile_cache.rs, src/shared/avatar.rs, src/sliding_sync.rs
Currently this commit only adds the usage of the user profile cache for the drawing of a profile (user name + avatar) for each timeline event.
Rewrite the avatar_cache to use a thread-local cache only accessible by the main UI thread (just like the user_profile_cache) instead of being based on the media cache.
Addresses #96
=> Use the user profile cache as a fallback for usernames/avatars

src/home/room_screen.rs
This avoids the confusion of using the same single `ReplyPreview` view for multiple purposes (an inline reply and a reply-to draft preview), and instead clarifies the intended usage of each view by using different views for those two purposes.
This also avoids the more complex logic of having to rememeber to mark certain subviews as visible or not.
=> Refactor `ReplyPreview` into component views

src/event_preview.rs, src/home/room_screen.rs, src/home/rooms_list.rs, src/lib.rs, src/sliding_sync.rs
Used for a preview of the latest message in each room of the rooms list, and for inline replies, both in the timeline and above the message input box when drafting a reply to an earlier message.
=> Use new `TextPreview` type to generate rich-Html previews of all events

src/home/room_screen.rs
This vastly simplifies the code clarity and logic of dealing with indices of PortalList items (`item_id`) vs. indices of Timeline items (`tl_idx`), as they are now the same value.
The `TopSpace` is not yet shown, as that is blocked on issue #132. Once that is addressed, we could show it as is, or animate it in and out using a fixed `height` that the animator modifies, and/or make it an overlay instead of a separate component that shifts the `Timeline` view down.
=> Move `TopSpace` out of `Timeline`'s PortalList and into `RoomScreen`

src/home/room_screen.rs, src/home/rooms_list.rs, src/home/rooms_sidebar.rs, src/home/spaces_dock.rs, src/profile/user_profile.rs, src/shared/avatar.rs, src/shared/html_or_plaintext.rs, src/shared/styles.rs, src/utils.rs
=> Minor UI improvements

Cargo.lock, src/home/main_content.rs, src/home/room_screen.rs
Addresses a few to-do items in `RoomScreen` state management, primarily the issue of a reply preview not actually being re-drawn upon switching back to a previously-drawn room.
Also, the message input box is automatically given keyboard focus after the user clicks the reply button for a message, making it much easier for the user to start typing a reply.
=> Save & restore replying-to preview state upon switching room timelines

src/shared/adaptive_view.rs
Fix AdaptiveView reverting to default variant selectors after DSL updates. 
Rooms sidebar would disappear on reloading because it it's variants never matched the default selector.
=> Do not override variant selectors on doc updates

Cargo.lock, Cargo.toml, login.toml, src/app.rs, src/event_preview.rs, src/lib.rs, src/persistent_state.rs, src/sliding_sync.rs
Fix CLI to accept server names instead of only fully-formed URLs.
Allow specifying the homserver on both the CLI and in `login.toml`.
=> Use `robius-directories` crate to support persistence on Android

src/home/rooms_list.rs, src/profile/user_profile.rs, src/sliding_sync.rs
This ensures that the room preview will have a latest message to display and that we'll be able to display some room history immediately upon a user opening a room timeline for the first time.
Also, use more Rusty and non-panic-ing code to access the rooms list while drawing room previews.
=> Pre-paginate each visible room in the rooms list once

src/home/room_screen.rs, src/sliding_sync.rs
Move the logic for processing background timeline updates to a separate function, such that we can run that procedure the very first time a room is opened. If any updates were processed, we immediately redraw the timeline, which removes all visible latency that previously existed, as previously, a timeline wouldn't be redrawn until the first pagination response was received.
There is one exception to this, which is when a timeline is cleared. It still gets drawn properly, but since it's been cleared, there is nothing that actually gets drawn.
This problem requires a completely separate solution, e.g., not actually setting the existing `TimelineUiState::items` field to the `new_items` vector from the TimelineUpdate until another (or several more) pagination responses have been received and …
=> Enable room history to be shown immediately upon first opening a room

src/home/room_screen.rs, src/shared/styles.rs
I refactored the font constants in the style to support fontfallthrough.
=> Fixed the bug where Chinese characters cannot be displayed

Cargo.lock, src/home/room_screen.rs
Disable send location button by default; it will be enabled upon receiving a valid location update.
=> Update to latest `robius-location` for linux to build properly

src/home/room_screen.rs
https://github.com/project-robius/robrix/issues/109
https://github.com/user-attachments/assets/4ca3a953-eb76-4f8a-8a65-f237682a9ef8
1. Set visibility for top_space when pagination is idle to true
2. Clear it when done_loading is true
3. Added send_pagination_request_based_on_scroll_pos function
=> Backward Paginate timeline by scroll #109

Cargo.lock, Cargo.toml, src/home/room_screen.rs, src/home/rooms_list.rs, src/sliding_sync.rs
Remove the separate pagination state subscriber task, which was previously being spawned once for every room. That was unnecessary and actually provided less information than just waiting for the result of the original task that actually called the paginate function.
Store the most-recently-scrolled-through item index in `TimelineUiState` such that we can determine whether when the user is scrolling upwards and has just hit the top-most item, at which point we fire off a backwards pagination request.
Closes #109
=> Completely redesign pagination code, support backwards pagination upon scroll

packaging/before-packaging-command/src/main.rs
The binary path doesn't actually need to exist before the release build completes, obviously. Remove this check.
=> before-packaging-command: the binary path may not exist

src/home/room_screen.rs
Fixes https://github.com/project-robius/robrix/issues/197
Uses RoomScreen 's WidgetId to filter actions created by Clicking Reply
Tested - won't open reply view in another chatroom
=> Only open a reply preview in the room screen where a message reply button was clicked

src/app.rs
Fixes #209
Since makepad is currently reseting the visibility (to the original value in the DSL) of the view on doc updates, we simply keep track of the login status at the app level and update visibility on `after_update_from_doc`.
=> Maintain login view visibility on doc updates

src/home/main_desktop_ui.rs
We caught a redraw loop in the `RoomScreen` instances, and the issue turned out to be calling `dock.select_tab` on an already selected tab constantly. The tab selection causes a redraw of the Dock which in turn was triggering a redraw of `MainDesktopUI` which was calling `select_tab` again unnecessarily and triggering a redraw cycle.
While this fixes the issue we want to soon improve this from the Dock side. I also have plans to improve its API to help keep track of open rooms, selected tabs, splitters, etc.
=> Do not re-select already selected rooms

.cargo/config.toml
Since we use these so prolifically, this reduces overall memory usage, allocation overhead, etc.
=> Use `Arc` instead of `Box` for ruma types like `OwnedRoomId`

Cargo.lock, Cargo.toml, src/home/rooms_list.rs
Closes #185.
Basically, this lays the groundwork for implementing a proper room search bar.
* `RoomsList::all_rooms` is now a HashMap that maps an `OwnedRoomId` key to a `RoomPreviewEntry` value. This being a hashmap implies that it has no ordering and is not used for determining display sort order or filtering.
* The list of `displayed_rooms` is stored separately as an ordered list of room IDs, which correspond to the specific order in which we want to display the list of rooms to the user.
* Introduced a `RoomDisplayFilter` function/closure type, which can be applied to all or part of the `all_rooms` map in order to produce the `displayed_rooms` ordered list above. This must be done manually since we don't want to have to recalculate it on every draw pass, but rather only occasionally …
=> Restructure the `RoomsList` to separate the storage of all rooms from the filtered display

src/home/rooms_list.rs, src/sliding_sync.rs
This approach *should* work, but I haven't been able to actually observe a room that has a tombstone event.
Working toward #178
=> Attempt to detect/handle tombstone rooms. No way to test it yet.

src/home/room_screen.rs
Fixed issue [#299](https://github.com/project-robius/robrix/issues/229)  . Apply a yellow background highlight to messages that mention the current user.
=> Apply a yellow background highlight to messages that mention the current logged-in user

Cargo.lock, src/home/room_screen.rs
The primary modifier key is Command on macOs and Ctrl on all other platforms. We now use this to add a shortcut that sends a message when you press `PrimaryModifier` + `Return`/`Enter` in the message input box.
=> Add Makepad feature to determine if a primary modifier key is pressed

src/app.rs, src/home/home_screen.rs, src/home/room_screen.rs, src/shared/styles.rs
Addresses the last two items of issue https://github.com/project-robius/robrix/issues/226
- The header was showing but with light colors that made it very hard to see
- Now we update the header title on navigation
- Added some padding to the back button
=> Display room name in the navigation stack view header

Cargo.lock, Cargo.toml, src/home/loading_modal.rs, src/home/mod.rs, src/home/room_screen.rs, src/sliding_sync.rs
Closes #223 
A modal is displayed while the backwards pagination requests are ongoing, and the user can cancel/abort the search if it's taking too long.
~~Tested to work for basic scenarios; probably still needs more testing. For example, I haven't tested the cancel feature yet, or the cleanup that happens if you close a RoomScreen while the modal is being displayed and the backwards pagination procedure is running in the background.~~
TODO before merging:
- cannot test this until the modal is fixed to not occupy the entire screen
=> Support backwards pagination until a target event is reached, with interactive user cancellation

Cargo.lock, Cargo.toml, src/home/room_screen.rs, src/shared/jump_to_bottom_button.rs
This changeset ensures that we don't scroll through potentially hundreds or thousands of items on the way to a much older message. There is now a maximum configurable window (number of items) that will be included in the scrolling animation, such that we don't get bogged down rendering thousands of items unnecessarily that barely get shown during the animation.
=> Use our improved `PortalList::smooth_scroll_to()` behavior

src/home/room_preview.rs, src/home/room_screen.rs, src/home/welcome_screen.rs, src/shared/html_or_plaintext.rs, src/shared/styles.rs
=> Display Notice and Emote messages properly

src/home/room_screen.rs, src/shared/text_or_image.rs
* Tweak the `TextOrImage` widget a bit to make it work better.
Still not perfect, but that's unrelated. At least the text shows up now.
* Show sticker/image plaintext `body` as part of loading/error messages
* This way the user will at least have some idea of what will be displayed or what was supposed to be displayed.
* remove overridden formatting for ImageMessage and CondensedImageMessage
=> Display Stickers as messages by re-using message display infra

src/home/room_preview.rs, src/home/room_screen.rs, src/home/rooms_list.rs, src/sliding_sync.rs
These are untested, since I cannot find any rooms used for server notices.
Also, obtain the `Tags` for each room and include them in the `RoomsListEntry` struct, which will allow the rooms_list to sort & filter rooms by details like `is_favourite` or `is_low_priority`.
=> Support displaying server notices

src/event_preview.rs, src/home/room_preview.rs, src/home/room_screen.rs, src/utils.rs, src/verification.rs
* This can probably be further improved to squash it a bit more, and also to add a fade/shadow effect towards the bottom in order to make the visual separation between room previews a bit clearer.
Other miscellaneous formatting improvements:
* Strip leading whitespace and whitespace-like HTML tags (`<p>`, `<br>`) from HTML-formatted messages, both in the timeline and in text previews. This helps avoid weird line breaks in small brief text previews.
* Make the location messages display a clickable `geo:` link.
=> Use a fixed height for room previews in the RoomsList

src/home/room_screen.rs, src/shared/adaptive_view.rs
This ensures other RoomScreen widget instances cannot possibly handle actions meant for a different RoomScreen accidentally.
This also fixes the issue of a single action being mistakenly handled multiple times (once per open RoomScreen instance), which results in a clicked link being opened 3 or 4 times instead of just once.
=> Capture and locally handle actions specific to a RoomScreen instance

Cargo.lock, src/home/room_screen.rs, src/profile/user_profile.rs, src/profile/user_profile_cache.rs, src/sliding_sync.rs
* Also, track in-flight fetch requests in order to ensure that redundant requests are not re-issued.
* Fix how user profile info is used in the user profile sliding pane, and ensure that an existing avatar image isn't replaced with a not-yet-loaded new one, until that new one is fully loaded.
* Do the same for user display names too.
=> Redesign user profile cache to fetch missing cache entries

Cargo.lock, src/home/light_themed_dock.rs, src/home/spaces_dock.rs, src/shared/color_tooltip.rs, src/shared/mod.rs, src/shared/verification_badge.rs
Closes #299 
1. Refactored VerificationBadge, encapsulating logic related to Badge state within the VerificationBadge component.  
2. Modify the tooltip display position to be relative to the Profile’s position.
3. Added a new ColorTooltip component, which can dynamically set the background color of the tooltip, such as automatically changing color based on the VerificationBadge state. 
4. Fixed the UI bug in [issue 299](https://github.com/project-robius/robrix/issues/299), which was caused by the `draw_depth` setting in `DockBase`, and it has been removed. The corresponding deletion will also be made in the Makepad widget code ( [Makepad PR #624](https://github.com/makepad/makepad/pull/624) ).
=> Refactor Verificatiion Badge and tooltip and Fixed Dock DrawDepth Bug

src/sliding_sync.rs
The original algorithm only returned the first character, so if the first character of the room name was a special character, it wouldn't show up in the user avatar. I modified the code to return the first valid character, ensuring the avatar displays properly. In the image above, the first and third rooms show correctly. Without this fix, it would return a `"?"`.
=> Skip the `@` char when displaying a room Avatar based on its name 

src/sliding_sync.rs
This PR contains some general cleanup & improvements that are follow-ups to PR #305. 
* When inspecting content from a new latest event that changed room power levels, we now look for not just an invitation being accepted but also for a general room Join action.
* When checking a user's power level to see if they can send a message, we now check against the current power levels required to send a message, not the room's default level. We only use the default power level as a backup.
=> Cleanup latest event handling; check room power levels accurately

src/home/room_preview.rs, src/shared/html_or_plaintext.rs
Change HTML link hover color, and prevent it from grabbing focus upon a FingerDown hit.
=> Minor UI tweaks: shorten RoomPreview to show exactly 2 lines of text

src/shared/text_or_image.rs
Currently, the width of the image in timeline, always equal to RoomScreen's width.
It was fixed now.
[Screencast from 2025-01-22 10-40-33.webm](https://github.com/user-attachments/assets/b449c7aa-3fac-4fff-88b3-f73ad3849461)
[Screencast from 2025-01-22 10-31-36.webm](https://github.com/user-attachments/assets/fe00f4a9-3e22-4c87-a2cc-4f292229ee10)
=> Display images at their actual size

src/home/loading_pane.rs, src/profile/user_profile.rs
~~Not quite working fully just yet.~~
Still pending some answers from Makepad about why hit handling isn't working as expected for KeyUp and FingerUp events in a given area.
We can still merge it now, though. Can fix FingerUp/KeyUp specifics at a later date.
=> Migrate Pane widgets to Makepad's `Hit` API instead of raw `Event`s

src/home/event_reaction_list.rs, src/home/spaces_dock.rs, src/profile/user_profile.rs, src/shared/verification_badge.rs
This vastly simplifies the `Profile` widget and allows the `VerificationBadge` widget to be almost entirely self-contained.
=> Redesign verification badge to handle Events as `Hit`s directly

src/home/room_screen.rs, src/sliding_sync.rs, src/utils.rs
We must apply the thumbnail format for the image anyhow it possess a thumbnail source or not.
Btw, an image won't possess a thumbnail source unless its size is larger than 500KB or so, by my test.
----
> Btw, an image won't possess a thumbnail source unless its size is larger than 500KB or so, by my test.
I found this by accident on deving, you can take a look (notice the size I marked)
=> Fix thumbnail

src/home/room_preview.rs
It's now split into a top part and a bottom part instead of left/right. The top part is the RoomName and latest timestamp, while the bottom part is the latest message content and then unread message/mentions badge.
=> Modify RoomPreview formatting to waste less whitespace

src/home/new_message_context_menu.rs, src/home/room_screen.rs, src/sliding_sync.rs
Always re-obtain the latest event in order to ensure that the latest message is no longer shown in the RoomsList room preview if that latest message has been deleted.
=> Implement deleting (redacting) a message from the context menu

Cargo.lock, src/home/room_preview.rs, src/home/rooms_list.rs
Relies on some of my new additions to Makepad, namely the ability to determine whether the PortalList was scrolling when a FingerDown Hit event occurred.
=> Don't handle hit events on the RoomsList while it's scrolling

Cargo.lock, src/home/room_screen.rs, src/home/rooms_list.rs
Update makepad dep to incorporate my improvements to the PortalList scroll handling logic, particularly for touchscreen devices that use drag scrolling.
Basically, this changeset ensures that touches/clicks on the PortalList *during* an existing scroll action are no longer treated as clicking the underlying item within the PortalList.
This is a follow-up/continuation to #394
=> Fix scroll behavior in rooms list (follow-up to #394)

Cargo.lock, src/utils.rs
Also ensure that all image loading functions within Robrix do not panic at all.
Fixes #382.
=> Update makepad with our fixes to avoid all panics in image decoding

src/home/editing_pane.rs, src/home/room_screen.rs
Adopt the same design as the EditingPane's header, which has better padding, a larger cancel button,
a centered boldfaced label describing the replying to behavior, and cancel-on-`Escape` behavior for the accompanying TextInput.
Closes #413
=> Redesign UI for the ReplyingPreview header

Cargo.lock, src/home/event_reaction_list.rs, src/home/loading_pane.rs, src/home/new_message_context_menu.rs, src/home/room_screen.rs, src/profile/user_profile.rs
Previously, the `BackPressed` event in Makepad wasn't handled correctly, and could not be properly represented via the `hits()` API.
Now, we have modified it in Makepad to include an internal `handled` boolean which is set to `true` once a widget has handled that event, ensuring that multiple widgets can't respond to a single `Backpressed`.
We also fixed the StackNavigation widget to ensure that it will only respond to a `BackPressed` event if no other child widget had already handled it previously.
Together, this fixes the issue where a UserProfileSlidingPane would be hidden *AND* the StackNavigation widget would return to the root RoomsList view upon a *single* `BackPressed` event. Now, it takes two separate `BackPressed` events for that to happen, which matches the user's expectations.
=> Use our latest Makepad update to fix duplicate Back button handling

Cargo.lock, Cargo.toml, src/home/event_reaction_list.rs, src/home/loading_pane.rs, src/home/new_message_context_menu.rs, src/home/room_preview.rs, src/home/room_read_receipt.rs, src/home/room_screen.rs, src/profile/user_profile.rs, src/shared/avatar.rs, src/shared/html_or_plaintext.rs, src/shared/verification_badge.rs
The general idea is to let child widgets handle a given event before their parent widget handles it.
If a given child widget handles that event, the parent widget won't handle it duplicately.
However, if no child widgets handle it, then the event will be able to be handled by the parent widget.
Now, a child widget can handle an event and then mark it as not-handled, meaning that another widget will *also* be able to handle it.
Note that this Makepad change still preserves the historical behavior of an event being marked as handled by default upon *any* call to `event.hits()`, so if you want to override that behavior, you have to explicitly call `EventHandled::mark_as_handled(false)` for that specific `Hit` variant.
This also removes the our use on the previous callback-based …
=> Use our new hit handling functionality in Makepad

Cargo.lock, src/home/event_reaction_list.rs, src/home/room_read_receipt.rs, src/shared/verification_badge.rs
Due to a minor display bug in CalloutTooltip,
we need to ensure that all emitted tooltip actions are also triggered on `FingerHoverIn` *and* `FingerHoverOver`, even though it ideally should not be necessary to re-trigger redundant tooltip actions on a simple `FingerHoverOver`.
=> Update makepad to include our recent fixes

src/app.rs
I have fixed the title of robrix, or more precisely, the `caption_label`, since the previous title was technically already in effect. On Windows, what is actually displayed is the `caption_label` within the `caption_bar`.
One issue is that in the widgets module `windows.rs`, the `caption_bar` has visible = false, but this setting does not take effect on Windows. This part needs to be specifically tracked in makepad.    
```rust
pub Window = <WindowBase> {
pass: { clear_color: (THEME_COLOR_BG_APP) }
flow: Down
nav_control: <NavControl> {}
caption_bar = <SolidView> {
// Here default is false, invalid for windows but macos is ok
visible: false,
flow: Right
draw_bg: {color: (THEME_COLOR_APP_CAPTION_BAR)}
height: 27,
caption_label = <View> {
width: Fill, height: Fill,
align: {x: 0.5, y: 0.5}, …
```
=> Fix: title from Makepad to Robrix for windows

src/home/room_screen.rs, src/shared/avatar.rs, src/shared/text_or_image.rs, src/sliding_sync.rs
This lint is slated to be added in Rust 1.86.
=> Fix `clippy::doc_overindented_list_items` lints

Cargo.lock, Cargo.toml, src/home/loading_pane.rs, src/home/new_message_context_menu.rs, src/home/room_preview.rs, src/home/room_screen.rs, src/profile/user_profile.rs, src/shared/avatar.rs
For things like `RoomPreview` and the `replied_to_messsage` above a given `Message` body, we handle hits on those widgets *before* we allow other child widgets to handle hits/events on themselves.
This ensure that sub-widgets within a `RoomPreview` or a `replied_to_message` view *cannot* handle a click (such a link, avatar), and that a click on one of those "parent" widgets just acts to select it and not interact with subwidgets within it.
=> Adopt new hit-handling logic, and fix clicks on reply previews

.gitignore, src/shared/mentionable_text_input.rs, src/shared/styles.rs
1. Resolved the issue of two highlights being produced in the @ user list when using arrow keys and the mouse. #450 
>  Depends on this Makepad pull request [#707](https://github.com/makepad/makepad/pull/707)
2. Resolved the issue of the mouse being unable to click and select a user.  #457
=> Fixed Bug : Issue 450 and Issue 457

src/home/home_screen.rs, src/home/rooms_list.rs, src/home/rooms_sidebar.rs, src/shared/mod.rs, src/shared/room_filter_input_bar.rs
The new `RoomFilterInputBar` is shared across both the narrow "Mobile"-oriented UI and the wider "Desktop"-oriented UI, and is now shown in different places on each.
We place the filter bar inside of a `CachedWidget` to ensure that there is only a singleton instance of the `RoomFilterInputBar` globally across the whole app.
This means that the text is now shared and that there is no need to filter its actions across multiple different SearchBar actions.
Thus, it now automatically works when transitioning between the mobile and desktop views.
Closes #474
=> Redesign `SearchBar` into a single shared `RoomFilterInputBar`

src/sliding_sync.rs
This pr would fix clippy warn for the new clippy warn standards added in Rust 1.78.
Note: The warn `std::io::Error::other` is actually fixed, **but i just disable clippy warn for large varient of the enum `MatrixRequest`**
=> Fix Rust 1.78 clippy warn.

Cargo.lock, Cargo.toml
Remove our own fork, which is no longer needed.
=> Update Makepad to track the new `dev` branch.

Cargo.toml, src/app.rs, src/home/invite_screen.rs, src/home/room_preview.rs, src/home/rooms_list.rs, src/join_leave_room_modal.rs, src/lib.rs, src/room/mod.rs, src/sliding_sync.rs, src/utils.rs, src/verification_modal.rs
This modal can also be used for joining or leaving any room, not just invited ones, but we don't yet have a UI to bring that up yet.
=> Add confirmation modal for accepting/rejecting a room invite

src/home/edited_indicator.rs, src/home/editing_pane.rs, src/home/mod.rs, src/home/room_screen.rs, src/join_leave_room_modal.rs, src/shared/mentionable_text_input.rs, src/shared/popup_list.rs
Closes #507.
Upon hover, the `EditedIndicator` will show the exact time/date of the most recent edit.
The feature to show the full edit history upon click is not yet impl'd.
=> Display when a message has been edited, beneath its timestamp

src/home/editing_pane.rs, src/home/room_screen.rs
Previously, we were re-using the `show_editing_pane()` function to act as a "restore state" function, but that has some issues. Now we have a dedicated save/restore function pair, and we also make sure to reset the state of the EditingPane if there was no pre-existing saved state to be restored.
=> Properly save/restore the state of the EditingPane

src/home/room_screen.rs
These are only accessible from the main UI thread, so there is no need to protect them with a full `Mutex`.
=> Use `thread_local` for storing saved timeline UI states

src/home/room_screen.rs
Fixes #475 
Previously blur hash decoding uses the image size. Large image results long decoding on the UI thread, causing UI hangs. Large image can be as wide as 4000 and height over 3000, but img.size_in_pixels(cx).unwrap_or_default() is only (640, 480).
Hence arbitrary small image size (640, 480) is used. 
https://github.com/user-attachments/assets/f4729008-a6cc-4028-9c8a-1cf295c4dff9
Blur hash with (640, 480) still preserves relatively good representation of the image.
=> Fix long blurhash decoding duration.

src/settings/settings_screen.rs, src/shared/confirmation_modal.rs, src/shared/mod.rs, src/tsp/mod.rs, src/tsp/tsp_settings_screen.rs, src/tsp/wallet_entry/mod.rs
Add general-purpose confirmation modal that can be used for any arbitrary action that requires showing an "are you sure" modal.
=> Implement feature to properly remove a TSP wallet from Robrix

src/sliding_sync.rs, src/tsp/mod.rs
This makes it easier to clean up, which is needed for PR #432. We now pass out `Handle`s instead of strong references to the runtime itself, which is fine because we do want to be able to drop the runtime and forcibly shutdown all background async tasks.
=> Store tokio Runtime instance as a single object not wrapped in Arc

Cargo.lock, Cargo.toml, src/app.rs, src/home/room_screen.rs, src/persistence/tsp_state.rs, src/profile/user_profile.rs, src/settings/account_settings.rs, src/shared/confirmation_modal.rs, src/shared/restore_status_view.rs, src/shared/styles.rs, src/sliding_sync.rs, src/tsp/create_did_modal.rs, src/tsp/create_wallet_modal.rs, src/tsp/mod.rs, src/tsp/tsp_settings_screen.rs, src/tsp/tsp_verification_modal.rs, src/tsp/verify_user.rs, src/tsp/wallet_entry/mod.rs, src/tsp_dummy/mod.rs, src/utils.rs
Implements item (1) from issue #551. (and part of (3), i suppose...)
~~Things are largely untested, but the basic UI and logic are there.~~ tested working, currently just on macOS and windows but it should work elsewhere too
~~TODO: still need to add a UI pane for accepting/rejecting an incoming TSP verification request (similar to the VerificationModal, but for TSP instead of Matrix-native verification requests).~~ done
Added a TSP section to the UserProfileSlidingPane that allows the user to enter a DID and associate it with another Matrix user ID, upon which a verification request will be sent to them. ~~(This is untested)~~ working
Fix issue where interactive events are delivered to the overlay views in the RoomScreen (UserProfileSlidingPane, LoadingPane).
=> Add infrastructure for verifying other users via TSP

src/home/room_screen.rs
Recently, a minor bug snuck in where it was possible for a message item's widget to have incomplete `MessageDetails`, because the related event ID was not always calculated but was still being re-set for the message item when it did not need to be re-set.
Now we only set it once when the message *content* is first drawn, which is correct in all cases, and also more efficient!
=> Ensure that message details are only set for a drawn item once
